/**
 * Markdown export of a plan into its workspace.
 *
 * The database stays the source of truth, but the user's global rules require a
 * plan file under `.dsh/plans/`, so every plan can be rendered as markdown with
 * checkboxes and written next to the project. The file carries a marker with the
 * plan id, which is how the writer tells its own files from hand-written ones:
 * a foreign file is never overwritten — the export then falls back to
 * `<slug>-<id>.md`.
 *
 * @module dsh-plan-store/core/export
 */
import { existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'

import { slugify } from './paths.js'
import type { PhaseTree, PlanTree, Task } from './types.js'

/** Prefix of the ownership marker written into every exported file. */
export const GENERATED_MARKER_PREFIX = '<!-- generated by dsh-plan-store'

/** Build the ownership marker of one plan. */
export function generatedMarker(planId: string): string {
  return `${GENERATED_MARKER_PREFIX}: ${planId} -->`
}

/** Options of {@link exportPlanToWorkspace}. */
export interface ExportOptions {
  /** Absolute workspace root that receives the file. */
  workspaceRoot: string
  /** Directory relative to the workspace root (default `.dsh/plans`). */
  exportDir: string
  /** Timestamp rendered into the file; defaults to now. */
  exportedAt?: string
}

/** Result of a write. */
export interface ExportWriteResult {
  /** Absolute path of the written file. */
  path: string
  /** True when a new file was created (false when an owned file was rewritten). */
  created: boolean
}

/** Render the checkbox marker of a task. */
function checkbox(task: Task): string {
  return task.status === 'done' ? '[x]' : '[ ]'
}

/** Render an optional status annotation for a task. */
function statusNote(task: Task): string {
  return task.status === 'doing' || task.status === 'blocked' ? ` _(${task.status})_` : ''
}

/** Render one task as a markdown list item with its notes and links. */
function renderTask(task: Task): string[] {
  const lines = [`- ${checkbox(task)} ${task.title}${statusNote(task)}`]
  const notes = task.notes.trim()
  if (notes.length > 0) {
    for (const line of notes.split(/\r?\n/u)) lines.push(`  ${line}`)
  }
  for (const link of task.links) lines.push(`  - ${link}`)
  return lines
}

/** Render one phase (heading, notes and tasks). */
function renderPhase(phase: PhaseTree, index: number): string[] {
  const lines = [`## Phase ${index + 1}: ${phase.title}`, '']
  const notes = phase.notes.trim()
  if (notes.length > 0) {
    lines.push(notes, '')
  }
  if (phase.tasks.length === 0) {
    lines.push('_No tasks._', '')
    return lines
  }
  for (const task of phase.tasks) lines.push(...renderTask(task))
  lines.push('')
  return lines
}

/** Render a whole plan as markdown with checkboxes. */
export function renderPlanMarkdown(tree: PlanTree, exportedAt: string): string {
  const lines: string[] = [generatedMarker(tree.id), `# ${tree.title}`, '']
  const description = tree.description.trim()
  if (description.length > 0) lines.push(description, '')
  lines.push(`- Status: ${tree.status}`)
  lines.push(`- Priority: ${tree.priority}`)
  if (tree.workspace.length > 0) lines.push(`- Workspace: ${tree.workspace}`)
  if (tree.tags.length > 0) lines.push(`- Tags: ${tree.tags.join(', ')}`)
  lines.push(`- Progress: ${tree.progress.done}/${tree.progress.total} tasks (${tree.progress.percent}%)`)
  lines.push(`- Exported: ${exportedAt} by dsh-plan-store`)
  lines.push('')
  if (tree.phases.length === 0) {
    lines.push('_No phases._', '')
  }
  tree.phases.forEach((phase, index) => {
    lines.push(...renderPhase(phase, index))
  })
  return `${lines.join('\n').replace(/\n{3,}/gu, '\n\n').trimEnd()}\n`
}

/** Preferred file name of a plan (`<slug>.md`). */
export function planExportFileName(plan: Pick<PlanTree, 'id' | 'title'>): string {
  return `${slugify(plan.title)}.md`
}

/** Disambiguated file name of a plan (`<slug>-<id>.md`). */
export function planExportFileNameWithId(plan: Pick<PlanTree, 'id' | 'title'>): string {
  const slug = slugify(plan.title)
  const short = plan.id.replace(/[^a-zA-Z0-9]+/gu, '')
  return `${slug}-${short}.md`
}

/** True when an existing file was written by this plugin for this plan. */
export function isOwnedBy(filePath: string, planId: string): boolean {
  try {
    const head = readFileSync(filePath, 'utf8').slice(0, 400)
    return head.includes(generatedMarker(planId))
  } catch {
    return false
  }
}

/** True when a path stays inside the target directory. */
function isInside(directory: string, filePath: string): boolean {
  const resolvedDir = dirname(join(directory, 'x'))
  const resolvedFile = dirname(filePath)
  return resolvedDir === resolvedFile && basename(filePath).length > 0
}

/**
 * Choose the file path for a plan without clobbering foreign files.
 *
 * A previously recorded `exportPath` inside the target directory wins, so a
 * renamed plan keeps its file. Otherwise `<slug>.md` is used when it is free or
 * owned by this plan, and `<slug>-<id>.md` when it belongs to someone else.
 */
export function resolveExportPath(tree: PlanTree, directory: string): string {
  const previous = tree.exportPath
  if (previous !== null && previous.length > 0 && isInside(directory, previous) && existsSync(previous)) {
    if (isOwnedBy(previous, tree.id)) return previous
  }
  const preferred = join(directory, planExportFileName(tree))
  if (!existsSync(preferred) || isOwnedBy(preferred, tree.id)) return preferred
  const fallback = join(directory, planExportFileNameWithId(tree))
  if (!existsSync(fallback) || isOwnedBy(fallback, tree.id)) return fallback
  return join(directory, `${slugify(tree.title)}-${Date.now().toString(36)}.md`)
}

/** Write the plan markdown into the workspace, atomically and without clobbering. */
export function exportPlanToWorkspace(tree: PlanTree, options: ExportOptions): ExportWriteResult {
  const workspaceRoot = options.workspaceRoot.trim()
  if (workspaceRoot.length === 0) throw new Error('The workspace root must not be empty.')
  const exportDir = options.exportDir.trim().length > 0 ? options.exportDir.trim() : '.dsh/plans'
  const directory = join(workspaceRoot, exportDir)
  mkdirSync(directory, { recursive: true })
  const target = resolveExportPath(tree, directory)
  const created = !existsSync(target)
  const exportedAt = options.exportedAt ?? new Date().toISOString()
  const markdown = renderPlanMarkdown(tree, exportedAt)
  const temporary = `${target}.tmp-${process.pid.toString(36)}`
  writeFileSync(temporary, markdown, 'utf8')
  try {
    renameSync(temporary, target)
  } catch (error) {
    try {
      unlinkSync(temporary)
    } catch {
      /* ignore */
    }
    throw error
  }
  return { path: target, created }
}
